name: Deploy to AWS Lambda

on:
  push:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1 
    - name: make install
      run: make install

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
    - name: serverless deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
