name: Deploy to AWS Lambda

on:
  push:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: checkout workspace
      uses: actions/checkout@v2
      with:
        fetch-depth: 1 
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: set up NPM
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: make ci
      run: |
        python -m pip install --upgrade pip
        make ci

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
    - name: serverless deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
